export const fieldList=[
    {
        prop:"remark",
        label:'备注',
        width:150
    },
    {
        prop:"gitRepositoryUrl",
        label:'Git仓库地址',
        width:150
    },
    {
        prop:"branch",
        label:'Git仓库分支',
        width:150
    },
    {
        prop:"workTree",
        label:'工作目录',
        width:150
    },
    {
        prop:"env",
        label:'Maven打包环境',
        width:150
    },
    {
        prop:"registryAddress",
        label:'推送镜像仓库地址',
        width:200
    },
    {
        prop:"operation",
        label:'操作',
        width:230,
        fixed:'right',
        slot:true
    }
]