export const fieldList=[
    {
        prop:"names",
        label:'容器名称',
        width:'150'
    },
    {
        prop:"ip",
        label:'节点IP',
        width:'150'
    },
    {
        prop:"image",
        label:'镜像',
        width:'150'
    },
    {
        prop:"command",
        label:'启动命令',
        width:'150'
    },
    {
        prop:"ports",
        label:'端口映射',
        width:'150'
    },
    {
        prop:"created",
        label:'创建多久',
        width:'150'
    },
    {
        prop:"status",
        label:'状态',
        width:'150'
    },
    {
        prop:"containerId",
        label:'容器ID',
        width:'150'
    },
    {
        prop:"operation",
        label:'操作',
        width:'230',
        slot:true,
        fixed:'right'
    }
]