server:
  port: 30880
spring:
  mvc:
    pathmatch:
      #兼容swagger2
      matching-strategy: ant_path_matcher
  application:
    name: cobweb-admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

cobweb:
  admin:
    cobweb-dump: /root/cobweb-dump
